- src/deep-resource/lib/Resource/Action.js
- src/deep-resource/lib/Resource/Exception/DirectLambdaCallDeniedException.js
- src/deep-resource/lib/Resource/Instance.js
- src/deep-resource/lib/Resource/Request.js
- src/deep-resource/test/Resource/Action.js
Deal with action.forceUserIdentity option
> Integrate forceUserIdentity option

- .travis.yml
- README.md
- src/deep-asset/README.md
- src/deep-cache/README.md
- src/deep-core/README.md
- src/deep-db/README.md
- src/deep-di/README.md
- src/deep-event/README.md
- src/deep-framework/README.md
- src/deep-fs/README.md
- src/deep-kernel/README.md
- src/deep-log/README.md
- src/deep-notification/README.md
- src/deep-resource/README.md
- src/deep-security/README.md
- src/deep-validation/README.md
- test/bin/coverage.sh
- test/package.json
Update readme files.
Update shell script.
Update package.json files
Add formating to .travis.yml
> Refactor coverage reporter from Coveralls to Codacy

- README.md
[DEEP Framework](https://github.com/MitocGroup/deep-framework) is a core component of the [Platform-as-a-Service](https://github.com/MitocGroup/deep-framework#appendix-b-deep-ecosystem) that abstracts web services from specific cloud providers like [Amazon Web Services](https://aws.amazon.com). This framework enables developers build web applications or platforms using [microservices architecture](https://en.wikipedia.org/wiki/Microservices) in a completely [serverless approach](https://github.com/MitocGroup/deep-framework#appendix-a-serverless-architecture).
> Improving documentation and support for deep-framework

- .houndignore
- src/deep-di/test/DI.js
Refactor unit tests in deep-di
> Refactor unit tests in deep-di

- .travis.yml
- src/deep-asset/package.json
- src/deep-cache/package.json
- src/deep-db/package.json
- src/deep-di/package.json
- src/deep-event/package.json
- src/deep-fs/package.json
- src/deep-kernel/package.json
- src/deep-log/package.json
- src/deep-notification/package.json
- src/deep-resource/package.json
- src/deep-security/package.json
- src/deep-validation/package.json
Adding functionality to pull local module version instead of npm repo version
> Adding functionality to pull local module version instead of npm repo version

- README.md
> Add code style grade

- src/deep-resource/test/Resource/Request.js
> Check response body

- .jshint.airbnb.json
> Add mocha to jshint

- src/deep-resource/test/Resource/LocalRequest.js
- src/deep-resource/test/Resource/Request.js
Update unit tests for Request/LocalRequest corresponding to the code changes
> Update unit tests for Request/LocalRequest

- .travis.yml
- docs/microservice.md
- src/deep-asset/package.json
- src/deep-cache/package.json
- src/deep-core/package.json
- src/deep-db/package.json
- src/deep-db/test/DB.js
- src/deep-di/package.json
- src/deep-event/package.json
- src/deep-framework/package.json
- src/deep-fs/package.json
- src/deep-kernel/package.json
- src/deep-log/package.json
- src/deep-notification/package.json
- src/deep-resource/package.json
- src/deep-security/lib/LocalToken.js
- src/deep-security/package.json
- src/deep-validation/package.json
- test/bin/coverage.sh
> Travis time optimize

- src/deep-security/lib/Token.js
Fixed identityId case on getter
> Fixed identityId case on getter

- src/deep-cache/lib/Driver/InMemoryDriver.js
- src/deep-cache/lib/Driver/LocalStorageDriver.js
Date.prototype.getTime() returns number of milliseconds
> LocalStorageCache milliseconds ttl fix

- src/deep-resource/lib/Resource/Request.js
Anticipate Object.assign in case of empty string for first argument
> Anticipate Object.assign in case of empty string for first argument

- src/deep-validation/test/Helpers/Joi.js
Upate tests corresponding to the code changes
> Upate tests corresponding to the code changes

- src/deep-cache/lib/Cache.js
- src/deep-cache/lib/Driver/LocalStorageDriver.js
Please refer to https://github.com/MitocGroup/deep-framework/issues/174
> #174 - Adjust deep-cache to fallback to in-memory driver if localStorage is not available

- src/deep-asset/node-bin/compile.sh
- src/deep-asset/node-bin/test.sh
- src/deep-cache/node-bin/compile.sh
- src/deep-cache/node-bin/test.sh
- src/deep-core/node-bin/compile.sh
- src/deep-core/node-bin/test.sh
- src/deep-db/node-bin/compile.sh
- src/deep-db/node-bin/test.sh
- src/deep-di/node-bin/compile.sh
- src/deep-di/node-bin/test.sh
- src/deep-event/node-bin/compile.sh
- src/deep-event/node-bin/test.sh
- src/deep-framework/node-bin/compile.sh
- src/deep-framework/node-bin/test.sh
- src/deep-fs/node-bin/compile.sh
- src/deep-fs/node-bin/test.sh
- src/deep-kernel/node-bin/compile.sh
- src/deep-kernel/node-bin/test.sh
- src/deep-log/node-bin/compile.sh
- src/deep-log/node-bin/test.sh
- src/deep-notification/node-bin/compile.sh
- src/deep-notification/node-bin/test.sh
- src/deep-resource/node-bin/compile.sh
- src/deep-resource/node-bin/test.sh
- src/deep-security/node-bin/compile.sh
- src/deep-security/node-bin/test.sh
- src/deep-validation/node-bin/compile.sh
- src/deep-validation/node-bin/test.sh
> Fix bash scripts

- src/deep-validation/test/Validation.js
Update unit tests for validateRuntimeInput()
> Update unit tests for validateRuntimeInput()

- src/deep-framework/node-bin/test.sh
- src/deep-framework/test/Framework.spec.js
Add unit tests for deep-framework
> Add unit tests for deep-framework

- src/deep-cache/test/Cache.spec.js
- src/deep-cache/test/Driver/AbstractFsDriver.spec.js
- src/deep-cache/test/Driver/CloudFrontDriver.spec.js
- src/deep-cache/test/Driver/S3FSDriver.spec.js
- src/deep-cache/test/Mocks/AbstractFsDriverMock.js
- src/deep-cache/test/Mocks/CloudFrontDriverMock.js
- src/deep-cache/test/Mocks/FSMock.js
- src/deep-cache/test/Mocks/RedisMock.js
- src/deep-cache/test/Mocks/S3FSDriverMock.js
- src/deep-cache/test/SharedCache.spec.js
- src/deep-resource/node-bin/test.sh
> Add unit test for deep-cache

- .travis.yml
- src/deep-fs/lib/Registry.js
Change travis version from 0.12 to 0.10
> Change travis version from 0.12 to 0.10

- src/deep-db/test/Mock/ModelMock.js
Fix ModelMock corresponding to the code changes
> Fix ModelMock corresponding to the code changes

- src/deep-core/test/AWS/Lambda/Response.spec.js
#186: Update core unit test for Response
> #186: Update core unit test for Response

- src/deep-kernel/package.json
- src/deep-kernel/test/Kernel.spec.js
#186: Update unit tests for deep-kernel
> #186: Update unit tests for deep-kernel

- src/deep-security/lib/Token.js
- src/deep-security/test/Token.spec.js
Update unit tests for deep-security
> Update unit tests for deep-security

- src/deep-resource/test/Mock/CacheMock.js
- src/deep-resource/test/Mock/RequestMock.js
- src/deep-resource/test/Resource/Action.spec.js
- src/deep-resource/test/Resource/Instance.spec.js
- src/deep-resource/test/Resource/LambdaResponse.spec.js
- src/deep-resource/test/Resource/LocalRequest.spec.js
- src/deep-resource/test/Resource/Request.spec.js
- src/deep-resource/test/Resource/Response.spec.js
- src/deep-resource/test/Resource/SuperagentResponse.spec.js
#186: Update unit tests for deep-resource
> #186: Update unit tests for deep-resource

- src/deep-core/test/AWS/Lambda/Response.spec.js
- src/deep-log/test/Driver/ConsoleDriver.spec.js
- src/deep-log/test/Log.spec.js
- src/deep-log/test/Mock/ConsoleDriverMock.js
#186: Update unit tests for deep-log
> #186: Update unit tests for deep-log

- src/deep-log/test/Mock/ConsoleDriverMock.js
> #186: Fix hound issues

- .travis.yml
- src/deep-asset/node-bin/compile.sh
- src/deep-cache/node-bin/compile.sh
- src/deep-core/node-bin/compile.sh
- src/deep-db/node-bin/compile.sh
- src/deep-di/node-bin/compile.sh
- src/deep-event/node-bin/compile.sh
- src/deep-framework/node-bin/compile.sh
- src/deep-fs/node-bin/compile.sh
- src/deep-kernel/node-bin/compile.sh
- src/deep-log/node-bin/compile.sh
- src/deep-notification/node-bin/compile.sh
- src/deep-resource/node-bin/compile.sh
- src/deep-security/node-bin/compile.sh
- src/deep-validation/node-bin/compile.sh
- test/bin/prepare_to_test.sh
- test/bin/replace_bootstrap_path.sh
Add skipping code transpiling to ES5 for travis
> Add skipping code transpiling to ES5 for travis

- bin/_head.sh
- bin/changelog.sh
- src/deep-framework/hooks/final_prepare_production.sh
- src/deep-framework/hooks/prepare_production.sh
> Update npm path usage

- src/deep-core/lib/AWS/Region.js
Add method for get region prefix
> Add method for get region prefix

- src/deep-resource/lib/Resource/SuperagentResponse.js
- src/deep-resource/test/Resource/SuperagentResponse.spec.js
#304 Incorrect error message when request falls with error
> #304 Incorrect error message when request falls with error

- src/deep-log/lib/Driver/RUM/AbstractEvent.js
Lambda called using useDirectCall are not logging events
> Fix direct called lambda logging bug

- .eslintrc
- .travis.yml
> Update to node v6.4

- .codeclimate.yml
- .eslintignore
- .eslintrc
- .travis.yml
- bin/install_precommit.sh
- bin/pre-commit
- docs/.codeclimate.yml
- docs/.eslintignore
- docs/.eslintrc
- docs/.travis.yml
- src/deep-core/lib/AWS/Lambda/Response.js
- src/deep-db/lib/DynamoDB/EventualConsistency.js
- tslint.json
> Add Typescript Linter

- .eslintignore
Update ignore rules for deep-root-*
> Update ignore rules for deep-root-*

- test/bin/node-scripts/GitHubMsgPublisher.es6
> Fix operator priorities issue

- src/deep-resource/test/Resource/Request.spec.js
> Remove temp usage of mock-aws

- .travis.yml
- bin/pre-commit
> Update node version

- docs/security/assets/aws-secure-deep-policy.json
Add new `dynamodb:TagResource` role
> Add new dynamodb role into doc
